name: 'Build Windows Module'
description: 'Sets up Windows environment and builds the module'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'

    - name: Add MinGW to PATH
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up
      run: make setup
      shell: bash

    - name: Build module
      run: make module.tar.gz
      shell: bash
